name: Build Windows App

on:
  push:
    paths:
      - 'windows-build.yml'
      - '**.py'
      - 'requirements.txt'
  workflow_dispatch:  # Allows manual runs

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install pyinstaller pdf2image pypdf2 pillow
          echo "Installing Poppler via Chocolatey..."
          choco install poppler --confirm  # Install Poppler on GitHub Actions
          
          # Find Poppler location and make sure it's accessible
          echo "Finding Poppler path..."
          POPPLER_PATH=$(where pdftoppm | findstr "poppler")
          echo "Found Poppler at: $POPPLER_PATH"
          echo "POPPLER_PATH=$POPPLER_PATH" >> $GITHUB_ENV

      - name: Build Windows Executable
        run: |
          pyinstaller --windowed --onefile --clean ^
            --add-data "%POPPLER_PATH%;poppler-bin" ^
            --icon="MaskGroup (1).ico" ^
            --name "PDFMerger" Pdf-Merger.py
        shell: cmd

        

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFMerger-Windows
          path: dist/PDFMerger.exe
