name: Build macOS App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest  # Runs on GitHub's macOS machine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install pyinstaller pdf2image pypdf2 pillow
          brew install poppler  # Install Poppler for PDF conversion

      - name: Build macOS App
        run: |
          pyinstaller --onefile --windowed --name "PDFMerger" Pdf-Merger.py

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFMerger-macOS
          path: dist/PDFMerger
