name: Build Windows App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest  # Runs on GitHub's Windows machine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install pyinstaller pdf2image pypdf2 pillow
          echo "Installing Poppler via Chocolatey..."
          choco install poppler --confirm  # Install Poppler on GitHub Actions

      - name: Set Poppler Path
        run: echo "POPPLER_PATH=%ChocolateyInstall%\lib\poppler\tools" >> $GITHUB_ENV

      - name: Build Windows Executable
        run: |
          pyinstaller --windowed --onefile --clean ^
            --add-data "%POPPLER_PATH%;poppler-24.08.0/Library/bin" ^
            --icon="C:\Users\Solan\Downloads\pdf things\Mask group (1).ico" ^
            --name "PDFMerger" Pdf-Merger.py
        shell: cmd  # Run in CMD to avoid PowerShell parsing issues

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFMerger-Windows
          path: dist/PDFMerger.exe
