name: Build Windows App

on:
    push:
      paths:
        - '.github/workflows/build-windows.yml'
        - '**.py'
        - 'requirements.txt'
    workflow_dispatch:
  

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install pyinstaller pdf2image pypdf2 pillow
          echo "Installing Poppler via Chocolatey..."
          choco install poppler --confirm
          
          # Find Poppler location
          echo "Finding Poppler path..."
          POPPLER_PATH=$(where pdftoppm | findstr "poppler")
          if [ -z "$POPPLER_PATH" ]; then
            echo "Error: Poppler not found!"
            exit 1
          fi
          echo "Found Poppler at: $POPPLER_PATH"
          echo "POPPLER_PATH=$POPPLER_PATH" >> $GITHUB_ENV

      - name: Build Windows Executable
        run: |
          pyinstaller --windowed --onefile --clean ^
            --add-data "%POPPLER_PATH%;." ^
            --icon="assets/MaskGroup.ico" ^
            --name "PDFMerger" Pdf-Merger.py
        shell: cmd

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFMerger-Windows
          path: dist/PDFMerger.exe
